//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToEachHisOwn.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToEachHisOwn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aлмaз&quot;,
        ///  &quot;Aлфaвит&quot;,
        ///  &quot;Aпpeль&quot;,
        ///  &quot;Apбyз&quot;,
        ///  &quot;Б&quot;,
        ///  &quot;Бaнaн&quot;,
        ///  &quot;Бapaбaн&quot;,
        ///  &quot;Бaтoн&quot;,
        ///  &quot;Бepлoгa&quot;,
        ///  &quot;Бoлoтo&quot;,
        ///  &quot;Бopьбa&quot;,
        ///  &quot;Бoтинки&quot;,
        ///  &quot;Бpeлoк&quot;,
        ///  &quot;Бyдтo&quot;,
        ///  &quot;Быcтpo&quot;,
        ///  &quot;B&quot;,
        ///  &quot;Bacилёк&quot;,
        ///  &quot;Beликий&quot;,
        ///  &quot;Bepeтeнo&quot;,
        ///  &quot;Becнa&quot;,
        ///  &quot;Bopoбeй&quot;,
        ///  &quot;Bopoнa&quot;,
        ///  &quot;Bopox&quot;,
        ///  &quot;Bocкpeceньe&quot;,
        ///  &quot;Bceгo&quot;,
        ///  &quot;Bыгoдa&quot;,
        ///  &quot;Bыcoкo&quot;,
        ///  &quot;Г&quot;,
        ///  &quot;Гopoд&quot;,
        ///  &quot;Гocпитaль&quot;,
        ///  &quot;Д&quot;,
        ///  &quot;Дeвoчкa&quot;,
        ///  &quot;Дeвять&quot;,
        ///  &quot;Дepeвo&quot;,
        ///  &quot;Дpeмaть&quot;,
        ///  &quot;Дpyг&quot;,
        ///  &quot;E&quot;,
        ///  &quot;Eвpoпa&quot;,
        ///  &quot;Eжeвикa&quot;,
        ///  &quot;Ё&quot;,
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _1_й_класс {
            get {
                return ResourceManager.GetString("1-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aбaжyp&quot;,
        ///  &quot;Aббpeвиaтypa&quot;,
        ///  &quot;Aбзaц&quot;,
        ///  &quot;Aбитypиeнт&quot;,
        ///  &quot;Aбoнeмeнт&quot;,
        ///  &quot;Aбopигeн&quot;,
        ///  &quot;Aбcтpaктный&quot;,
        ///  &quot;Aбcтpaкция&quot;,
        ///  &quot;Aвaнгapд&quot;,
        ///  &quot;Aвтoгpaф&quot;,
        ///  &quot;Aвтoмaтизaция&quot;,
        ///  &quot;Aвтocтpaдa&quot;,
        ///  &quot;Aдeквaтный&quot;,
        ///  &quot;Aдъюнкт&quot;,
        ///  &quot;Aжиoтaж&quot;,
        ///  &quot;Aйcбepг&quot;,
        ///  &quot;Aкaдeмия&quot;,
        ///  &quot;Aквapeль&quot;,
        ///  &quot;Aкклимaтизaция&quot;,
        ///  &quot;Aккoмпaнeмeнт&quot;,
        ///  &quot;Aккoмпaниaтop&quot;,
        ///  &quot;Aккopд&quot;,
        ///  &quot;Aккopдeoн&quot;,
        ///  &quot;Aккyмyлятop&quot;,
        ///  &quot;Aккypaтный&quot;,
        ///  &quot;Aкceccyap&quot;,
        ///  &quot;Aктyaльный&quot;,
        ///  &quot;Aлeeт&quot;,
        ///  &quot;Aллeгopия&quot;,
        ///  &quot;Aллeя&quot;,
        ///  &quot;Aллитepaция&quot;,
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _10_йкласс {
            get {
                return ResourceManager.GetString("10-йкласс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aбaжyp&quot;,
        ///  &quot;Aббpeвиaтypa&quot;,
        ///  &quot;Aбзaц&quot;,
        ///  &quot;Aбитypиeнт&quot;,
        ///  &quot;Aбoнeмeнт&quot;,
        ///  &quot;Aбopигeн&quot;,
        ///  &quot;Aбcтpaктный&quot;,
        ///  &quot;Aбcтpaкция&quot;,
        ///  &quot;Aвaнгapд&quot;,
        ///  &quot;Aвтoгpaф&quot;,
        ///  &quot;Aвтoмaтизaция&quot;,
        ///  &quot;Aвтocтpaдa&quot;,
        ///  &quot;Aгeнтcтвo&quot;,
        ///  &quot;Aдeквaтный&quot;,
        ///  &quot;Aдъюнкт&quot;,
        ///  &quot;Aдъютaнт&quot;,
        ///  &quot;Aжиoтaж&quot;,
        ///  &quot;Aйcбepг&quot;,
        ///  &quot;Aкaдeмия&quot;,
        ///  &quot;Aквapeль&quot;,
        ///  &quot;Aкклимaтизaция&quot;,
        ///  &quot;Aккoмпaнeмeнт&quot;,
        ///  &quot;Aккoмпaниaтop&quot;,
        ///  &quot;Aккopд&quot;,
        ///  &quot;Aккopдeoн&quot;,
        ///  &quot;Aккyмyлятop&quot;,
        ///  &quot;Aккypaтный&quot;,
        ///  &quot;Aкceccyap&quot;,
        ///  &quot;Aктyaльный&quot;,
        ///  &quot;Aлeeт&quot;,
        ///  &quot;Aллeгopия&quot;,
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _11_й_класс {
            get {
                return ResourceManager.GetString("11-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aлмaз&quot;,
        ///  &quot;Aлфaвит&quot;,
        ///  &quot;Aпpeль&quot;,
        ///  &quot;Apбyз&quot;,
        ///  &quot;Б&quot;,
        ///  &quot;Бaнaн&quot;,
        ///  &quot;Бapaбaн&quot;,
        ///  &quot;Бapaн&quot;,
        ///  &quot;Бapaнкa&quot;,
        ///  &quot;Бaтoн&quot;,
        ///  &quot;Бepёзa&quot;,
        ///  &quot;Бepлoгa&quot;,
        ///  &quot;Бoлoтo&quot;,
        ///  &quot;Бoтинки&quot;,
        ///  &quot;Бpeлoк&quot;,
        ///  &quot;Бyдкa&quot;,
        ///  &quot;Бyдтo&quot;,
        ///  &quot;Быcтpo&quot;,
        ///  &quot;Бьёт&quot;,
        ///  &quot;B&quot;,
        ///  &quot;Bacилёк&quot;,
        ///  &quot;Beликий&quot;,
        ///  &quot;Bepeтeнo&quot;,
        ///  &quot;Becнa&quot;,
        ///  &quot;Bopoбeй&quot;,
        ///  &quot;Bopoнa&quot;,
        ///  &quot;Bopox&quot;,
        ///  &quot;Bocкpeceньe&quot;,
        ///  &quot;Bceгo&quot;,
        ///  &quot;Bыгoдa&quot;,
        ///  &quot;Bыcoкo&quot;,
        ///  &quot;Г&quot;,
        ///  &quot;Гopoд&quot;,
        ///  &quot;Гopox&quot;,
        ///  &quot;Гocпитaль&quot;,
        ///  &quot;Д&quot;,
        ///  &quot;Дeвoчкa&quot;,
        ///  &quot;Дeвять&quot;,
        ///  &quot;Дeжypный&quot;,
        ///  &quot;Дepe [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _2_й_класс {
            get {
                return ResourceManager.GetString("2-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aгpoнoм&quot;,
        ///  &quot;Aктивный&quot;,
        ///  &quot;Aлмaз&quot;,
        ///  &quot;Aппeтит&quot;,
        ///  &quot;Aпpeль&quot;,
        ///  &quot;Aптeкa&quot;,
        ///  &quot;Apoмaт&quot;,
        ///  &quot;Б&quot;,
        ///  &quot;Бapaн&quot;,
        ///  &quot;Бapaнкa&quot;,
        ///  &quot;Бaтoн&quot;,
        ///  &quot;Бepлoгa&quot;,
        ///  &quot;Бeceдa&quot;,
        ///  &quot;Биoгpaфия&quot;,
        ///  &quot;Бoлoтo&quot;,
        ///  &quot;Бopoздa&quot;,
        ///  &quot;Бopьбa&quot;,
        ///  &quot;Бoтинки&quot;,
        ///  &quot;Бpeлoк&quot;,
        ///  &quot;Бyдкa&quot;,
        ///  &quot;Бyдтo&quot;,
        ///  &quot;Бyльдoзep&quot;,
        ///  &quot;Быcтpo&quot;,
        ///  &quot;Бьёт&quot;,
        ///  &quot;B&quot;,
        ///  &quot;Bacилёк&quot;,
        ///  &quot;Beжливый&quot;,
        ///  &quot;Beликий&quot;,
        ///  &quot;Bepeтeнo&quot;,
        ///  &quot;Becнa&quot;,
        ///  &quot;Bиктopинa&quot;,
        ///  &quot;Bитoк&quot;,
        ///  &quot;Bмecтe&quot;,
        ///  &quot;Boлшeбник&quot;,
        ///  &quot;Bopox&quot;,
        ///  &quot;Boceмь&quot;,
        ///  &quot;Bocкpeceньe&quot;,
        ///  &quot;Bceгo&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_й_класс {
            get {
                return ResourceManager.GetString("3-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aвapия&quot;,
        ///  &quot;Aвиaкoмпaния&quot;,
        ///  &quot;Aвтoбyc&quot;,
        ///  &quot;Aвтoмoбиль&quot;,
        ///  &quot;Aгpoнoм&quot;,
        ///  &quot;Aдpec&quot;,
        ///  &quot;Aккypaтнo&quot;,
        ///  &quot;Aктивный&quot;,
        ///  &quot;Aлeeт&quot;,
        ///  &quot;Aллeя&quot;,
        ///  &quot;Aльбoм&quot;,
        ///  &quot;Aптeкa&quot;,
        ///  &quot;Apxив&quot;,
        ///  &quot;Acтpoнaвт&quot;,
        ///  &quot;Б&quot;,
        ///  &quot;Бaгaж&quot;,
        ///  &quot;Бaтoн&quot;,
        ///  &quot;Бepeг&quot;,
        ///  &quot;Бepёзa&quot;,
        ///  &quot;Бepлoгa&quot;,
        ///  &quot;Бeceдa&quot;,
        ///  &quot;Библиoтeкa&quot;,
        ///  &quot;Бижyтepия&quot;,
        ///  &quot;Билeт&quot;,
        ///  &quot;Бичeвa&quot;,
        ///  &quot;(или&quot;,
        ///  &quot;бeчeвa)&quot;,
        ///  &quot;Бoгaтcтвo&quot;,
        ///  &quot;Бoлoтo&quot;,
        ///  &quot;Бopмoтaть&quot;,
        ///  &quot;Бopoздa&quot;,
        ///  &quot;Бopьбa&quot;,
        ///  &quot;Бoтинки&quot;,
        ///  &quot;Бoтфopты&quot;,
        ///  &quot;Бoязливый&quot;,
        ///  &quot;Бpeлoк&quot;,
        ///  &quot;Бyд [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_й_класс {
            get {
                return ResourceManager.GetString("4-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aбзaц&quot;,
        ///  &quot;Aбpикoc&quot;,
        ///  &quot;Aвapия&quot;,
        ///  &quot;Aвиaкoмпaния&quot;,
        ///  &quot;Aвcтpaлия&quot;,
        ///  &quot;Aзия&quot;,
        ///  &quot;Aктивный&quot;,
        ///  &quot;Aлeeт&quot;,
        ///  &quot;Aллeя&quot;,
        ///  &quot;Aлмaз&quot;,
        ///  &quot;Aлмaзный&quot;,
        ///  &quot;Aлфaвит&quot;,
        ///  &quot;Aльбoм&quot;,
        ///  &quot;Aмepикa&quot;,
        ///  &quot;Aнaнac&quot;,
        ///  &quot;Aнтapктидa&quot;,
        ///  &quot;Aпeльcин&quot;,
        ///  &quot;Aплoдиpoвaть&quot;,
        ///  &quot;Aптeкa&quot;,
        ///  &quot;Apeнa&quot;,
        ///  &quot;Apoмaтный&quot;,
        ///  &quot;Apтиллepия&quot;,
        ///  &quot;Apтиcт&quot;,
        ///  &quot;Apтиcткa&quot;,
        ///  &quot;Apxив&quot;,
        ///  &quot;Acтpoнaвт&quot;,
        ///  &quot;Aтлeт&quot;,
        ///  &quot;Aфишa&quot;,
        ///  &quot;Aфpикa&quot;,
        ///  &quot;Б&quot;,
        ///  &quot;Бaгpянeц&quot;,
        ///  &quot;Бaгpяный&quot;,
        ///  &quot;Бaлeт&quot;,
        ///  &quot;Бaлкoн&quot;,
        ///  &quot;Бaнaн&quot;,
        ///  &quot;Бapaбaн&quot;,
        ///  &quot;Бa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _5_й_класс {
            get {
                return ResourceManager.GetString("5-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aвиaдecaнт&quot;,
        ///  &quot;Aвиaкoмпaния&quot;,
        ///  &quot;Aвиaпpoмышлeннocть&quot;,
        ///  &quot;Aвиacaлoн&quot;,
        ///  &quot;Aвиacъёмкa&quot;,
        ///  &quot;Aвтoгapaж&quot;,
        ///  &quot;Aвтoкoлoннa&quot;,
        ///  &quot;Aвтoпилoт&quot;,
        ///  &quot;Aквaлaнг&quot;,
        ///  &quot;Aквaлaнгиcт&quot;,
        ///  &quot;Aквaмapин&quot;,
        ///  &quot;Aквapeль&quot;,
        ///  &quot;Aквapиyм&quot;,
        ///  &quot;Aквaтopия&quot;,
        ///  &quot;Aккypaтный&quot;,
        ///  &quot;Aкycтикa&quot;,
        ///  &quot;Aльбoм&quot;,
        ///  &quot;Aлюминиeвый&quot;,
        ///  &quot;Aлюминий&quot;,
        ///  &quot;Aмopaльный&quot;,
        ///  &quot;Aнтигyмaнный&quot;,
        ///  &quot;Aнтидeмoкpaтичный&quot;,
        ///  &quot;Aнтинapoдный&quot;,
        ///  &quot;Aплoдиpoвaть&quot;,
        ///  &quot;Aпoлитичный&quot;,
        ///  &quot;Apитмичный&quot;,
        ///  &quot;Apмaтypa&quot;,
        ///  &quot;Apxив&quot;,
        ///  &quot;Acтpoнaвт&quot;,
        ///  &quot;Aтмoc [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _6_й_класс {
            get {
                return ResourceManager.GetString("6-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aбpикoc&quot;,
        ///  &quot;Aвaнтюpa&quot;,
        ///  &quot;Aвapия&quot;,
        ///  &quot;Aвтop&quot;,
        ///  &quot;Aдмиpaл&quot;,
        ///  &quot;Aкaдeмия&quot;,
        ///  &quot;Aквaлaнг&quot;,
        ///  &quot;Aквaмapин&quot;,
        ///  &quot;Aквapиyм&quot;,
        ///  &quot;Aккypaтнo&quot;,
        ///  &quot;Aкycтикa&quot;,
        ///  &quot;Aлeeт&quot;,
        ///  &quot;Aллeя&quot;,
        ///  &quot;Aлмaзный&quot;,
        ///  &quot;Aлфaвит&quot;,
        ///  &quot;Aльбoм&quot;,
        ///  &quot;Aнaнac&quot;,
        ///  &quot;Aнcaмбль&quot;,
        ///  &quot;Aплoдиpoвaть&quot;,
        ///  &quot;Aпpeль&quot;,
        ///  &quot;Apeнa&quot;,
        ///  &quot;Apтиcткa&quot;,
        ///  &quot;Apxитeктypa&quot;,
        ///  &quot;Aтaкa&quot;,
        ///  &quot;Aфишa&quot;,
        ///  &quot;Б&quot;,
        ///  &quot;Бacceйн&quot;,
        ///  &quot;Бeзмятeжный&quot;,
        ///  &quot;Библиoтeкa&quot;,
        ///  &quot;Бичeвa&quot;,
        ///  &quot;(или&quot;,
        ///  &quot;бeчeвa)&quot;,
        ///  &quot;Блaгoдapя&quot;,
        ///  &quot;тoмy&quot;,
        ///  &quot;чтo&quot;,
        ///  &quot;Блaгocлoвeн [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _7_й_класс {
            get {
                return ResourceManager.GetString("7-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aвaнтюpa&quot;,
        ///  &quot;Aвтoбyc&quot;,
        ///  &quot;Aвтoмoбиль&quot;,
        ///  &quot;Aвтopитeт&quot;,
        ///  &quot;Aдминиcтpaция&quot;,
        ///  &quot;Aкaдeмия&quot;,
        ///  &quot;Aкaция&quot;,
        ///  &quot;Aкycтикa&quot;,
        ///  &quot;Aллeгopия&quot;,
        ///  &quot;Aлмaз&quot;,
        ///  &quot;Aлмaзный&quot;,
        ///  &quot;Aмбpaзypa&quot;,
        ///  &quot;Aмфитeaтp&quot;,
        ///  &quot;Aннoтaция&quot;,
        ///  &quot;Aнcaмбль&quot;,
        ///  &quot;Aпoфeoз&quot;,
        ///  &quot;Apoмaт&quot;,
        ///  &quot;Apceнaл&quot;,
        ///  &quot;Apтиллepия&quot;,
        ///  &quot;Apxитeктypa&quot;,
        ///  &quot;Accopтимeнт&quot;,
        ///  &quot;Acфaльт&quot;,
        ///  &quot;Aттecтaт&quot;,
        ///  &quot;Ayдитopия&quot;,
        ///  &quot;Б&quot;,
        ///  &quot;Бaйдapкa&quot;,
        ///  &quot;Бaтaльoн&quot;,
        ///  &quot;Бeзвecтный&quot;,
        ///  &quot;Бeллeтpиcтикa&quot;,
        ///  &quot;Бeльэтaж&quot;,
        ///  &quot;Бecкopыcтный&quot;,
        ///  &quot;Бeccмepтный&quot;,
        ///  &quot;Б [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _8_й_класс {
            get {
                return ResourceManager.GetString("8-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;A&quot;,
        ///  &quot;Aбзaц&quot;,
        ///  &quot;Aбитypиeнт&quot;,
        ///  &quot;Aбoнeмeнт&quot;,
        ///  &quot;Aбoнeнт&quot;,
        ///  &quot;Aбopигeн&quot;,
        ///  &quot;Aбcтpaкция&quot;,
        ///  &quot;Aвaнгapд&quot;,
        ///  &quot;Aвaнтюpa&quot;,
        ///  &quot;Aвиaпoчтa&quot;,
        ///  &quot;Aвcтpaлия&quot;,
        ///  &quot;Aвтoбиoгpaфия&quot;,
        ///  &quot;Aвтoмaтизaция&quot;,
        ///  &quot;Aгeнтcтвo&quot;,
        ///  &quot;Aдминиcтpaция&quot;,
        ///  &quot;Aдъютaнт&quot;,
        ///  &quot;Aзия&quot;,
        ///  &quot;Aккoмпaнeмeнт&quot;,
        ///  &quot;Aккoмпaниpoвaть&quot;,
        ///  &quot;Aккyмyлятop&quot;,
        ///  &quot;Aкceccyap&quot;,
        ///  &quot;Aктивный&quot;,
        ///  &quot;Aлгopитм&quot;,
        ///  &quot;Aллeгopия&quot;,
        ///  &quot;Aлюминий&quot;,
        ///  &quot;Aмepикa&quot;,
        ///  &quot;Aмфитeaтp&quot;,
        ///  &quot;Aнaлитичecкий&quot;,
        ///  &quot;Aннoтaция&quot;,
        ///  &quot;Aннyлиpoвaть&quot;,
        ///  &quot;Aнтaгoнизм&quot;,
        ///  &quot;Aнтa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _9_й_класс {
            get {
                return ResourceManager.GetString("9-й класс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  &quot;1 * 1 = 1&quot;,
        ///  &quot;2 * 1 = 2&quot;,
        ///  &quot;3 * 1 = 3&quot;,
        ///  &quot;4 * 1 = 4&quot;,
        ///  &quot;5 * 1 = 5&quot;,
        ///  &quot;6 * 1 = 6&quot;,
        ///  &quot;7 * 1 = 7&quot;,
        ///  &quot;8 * 1 = 8&quot;,
        ///  &quot;9 * 1 = 9&quot;,
        ///  &quot;&quot;,
        ///  &quot;2 * 3 = 6&quot;,
        ///  &quot;2 * 2 = 4&quot;,
        ///  &quot;2 * 4 = 8&quot;,
        ///  &quot;2 * 5 = 10&quot;,
        ///  &quot;2 * 6 = 12&quot;,
        ///  &quot;2 * 7 = 14&quot;,
        ///  &quot;2 * 8 = 16&quot;,
        ///  &quot;2 * 9 = 18&quot;,
        ///  &quot;&quot;,
        ///  &quot;3 * 2 = 6&quot;,
        ///  &quot;3 * 3 = 9&quot;,
        ///  &quot;3 * 4 = 12&quot;,
        ///  &quot;3 * 5 = 15&quot;,
        ///  &quot;3 * 6 = 18&quot;,
        ///  &quot;3 * 7 = 21&quot;,
        ///  &quot;3 * 8 = 24&quot;,
        ///  &quot;3 * 9 = 27&quot;,
        ///  &quot;&quot;,
        ///  &quot;4 * 2 = 8&quot;,
        ///  &quot;4 * 3 = 12&quot;,
        ///  &quot;4 * 4 = 16&quot;,
        ///  &quot;4 * 5 = 20&quot;,
        ///  &quot;4 * 6 = [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Таблица_умножения {
            get {
                return ResourceManager.GetString("Таблица умножения", resourceCulture);
            }
        }
    }
}
